---
platform: linux

image_resource:
  type: docker-image
  source:
    - repository: suhligibm/ci-pmc-notes

inputs:
  - name: pipeline
  - name: html

params:
  HTML_FILE:
  MAILGUN_API_KEY:

run:
  path: pipeline/tasks/notification/task.sh
