---
platform: linux

image_resource:
  type: docker-image
  source:
    - repository: suhligibm/ruby-ci-image

inputs:
  - name: markdown
  - name: pipeline

outputs:
  - name: html

params:
  MARKDOWN_FILE:
  HTML_FILE:
  BUNDLE_GEMFILE: pipeline/tasks/md2html/Gemfile

run:
  path: pipeline/tasks/md2html/md2html.sh
