---
platform: linux

image_resource:
  type: docker-image
  source:
    - repository: suhligibm/ci-ruby-base

inputs:
  - name: gemfiles
  - name: dockerfiles
  - name: pipeline

outputs:
  - name: target

run:
  path: pipeline/tasks/collect-image-files/task.sh
