resources:
- name: pipeline
  type: git
  source:
    uri: https://github.com/suhlig/pmc-notification
    branch: master
    paths: [ docker/ruby/Dockerfile ]

- name: Ruby CI Image
  type: docker-image
  source:
    repository: suhligibm/ruby-ci-image
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}

jobs:
- name: Create Ruby CI image
  plan:
  - get: pipeline
    trigger: true
  - put: Ruby CI Image
    params: { build: pipeline/docker/ruby }
