resources:
  - name: pipeline
    type: git
    source:
      uri: https://github.com/suhlig/pmc-notification
      branch: master
      paths: ["tasks/*"]

  - name: runtime-pmc-notes
    type: git
    source:
      uri: https://github.com/cloudfoundry/pmc-notes
      branch: master
      paths: ["Runtime/*"]

jobs:
  - name: Notify on new Runtime PMC notes
    plan:
      - get: runtime-pmc-notes
        trigger: true

      - get: pipeline
        trigger: false

      - task: Convert Markdown to HTML
        file: pipeline/tasks/md2html/task.yml
        input_mapping:
          - markdown: runtime-pmc-notes
        params:
          HTML_FILE: html/output.html
        attempts: 3

      - task: Send notification
        file: pipeline/tasks/notification/task.yml
        params:
          MAILGUN_API_KEY: {{mailgun-api-key}}
          SUBJECT: Runtime PMC Meeting Notes
          HTML_FILE: html/output.html
